### ISSUE TITLE
Extend @params to fetch test parameters from a given ParameterProvider interface implementation or a ParameterGenerator generator function

### ISSUE THREAD

**Issue by silkentrance** [testdeck/testdeck#144]
The current solution for parameterised tests is great but it lacks the ease of editing / adding additional parameter sets for a given test method to the system or to even customise the way that the test parameters are being generated/provided.

## Proposed Solution

Pseudo Code!
```
@suite
class Suite {
  @params(CustomParameterProvider)
  test({ p1, p2, p3, p4 }): void { 
    // ...
  }
  @params(customParameterGenerator)
  test2({ p1, p2, p3, p4 }): void { 
    // ...
  }
}

interface ParameterProvider {
  *params(): any;
}

typedef ParameterGenerator = *() => any;

class CustomParameterProvider implements ParameterProvider {
  *params() : any {
     yield { a: 'a', b: 'b', c: 'c', d: 'd' };
  }
}

function *customParameters(): any {
     yield { a: 'a', b: 'b', c: 'c', d: 'd' };
}
```

### JUnit 5

JUnit 5 allows the user to parameterise their test methods via custom parameter providers.

**Comment by sskorol** [comment]
Hey @silkentrance @pana-cc,

Very cool library! Especially for people who came from other languages like Java.
Couple of years ago I was poking around [mocha-typescript](https://www.npmjs.com/package/mocha-typescript) and found it really useful for my system tests. However, I missed some important features I'd really love to see: more flexible data provider and custom extension points.

I'm an author of a [test-data-supplier](https://github.com/sskorol/test-data-supplier) library written in Java. So probably, I can share some thoughts on this feature. My initial point was to add an opportunity to supply any data type as a test's input, so that a single test could be splitted into N (depending on a type), where N = length of the provided iterative structure or just a single object. The main concept was taken from [TestNG](https://github.com/cbeust/testng) `DataProvider`.

So when I played with mocha-typescript, it didn't seem very convenient adding N similar `params` decorators for each dataset I wanted to supply. Moreover, I couldn't find the way to change this behaviour. That's how a pet [ts-test-decorators](https://github.com/sskorol/ts-test-decorators) library appeared. I had to modify a part of mocha-typescript related to params' processing to support functions and custom injections, so that anyone can use an external function as a data provider the following way:
```ts
@suite
class AuthorizationTests {
  @data(testData())
  @data.withCustomTestName(user => `${user} should be able to sign`)
  userShouldBeAbleToSignIn(user: User) {
    open(LoginPage)
      .loginWith(user)
      .select(ProfilePage);
    
    verifyThat(atProfilePage)
      .fullNameIs(user.fullName)
      .usernameIs(user.username);
  }
}
    
function testData(): Array<User> {
  return [
    new User('stranger', '123456', 'Strange Person'),
    new User('test', '123456', 'Test User')
  ];
}
```
However, it doesn't see OOP-like. Moreover, as far I understood, we cannot get class-level `this` from within decorator's context (please correct me if I'm wrong). The next thing I tried (already with `testdeck`) was the following `makeParamsFunction` modification:
```ts
function makeParamsFunction(execution?: Execution): any {
  return (params: any, name?: string) => {
    return (target: any, propertyKey: string, descriptor: PropertyDescriptor) => {
      const adjustedParams = typeof params === 'function' ? params() : params
      target[propertyKey][testNameSymbol] = propertyKey.toString()
      target[propertyKey][parametersSymbol] = target[propertyKey][parametersSymbol] || [];
      [].concat(adjustedParams || []).forEach(param => {
        target[propertyKey][parametersSymbol].push({ execution, name, params: param })
      })
      return processDescriptor(
        args => JSON.stringify(args),
        arg => getReporter().addArgument('inputs', arg),
        descriptor
      )
    }
  }
}
```
This lets me doing the following:
```ts
@suite
class GitHubTests {
  static authData = (): User[] => [
    new User('user1', 'password1', 'Full Name 1'),
    new User('user2', 'password2', 'Full Name 2')
  ]

  @params(GitHubTests.authData)
  @params.naming((user: User) => `${user.fullName} should be able to sign`)
  public userShouldBeAbleToSignIn(user) {
    open(GuestPage)
      .signInWith(user)
      .expandProfileMenu()

    verifyThat(atHomePage).usernameIs(user.username)
  }
}
```
It's not lazy, but at least we can avoid writing N decorators for a single test case (that might be painful in case of a big number of data).

On the other hand, I still can't override this behaviour, that forces me copy/pasting some core code to inject custom metadata:
```ts
function makeParamsFunction(execution?: Execution): any {
  return (params: any, name?: string) => {
    return (target: any, propertyKey: string, descriptor: PropertyDescriptor) => {
      const adjustedParams = typeof params === 'function' ? params() : params
      target[propertyKey][testNameSymbol] = propertyKey.toString()
      target[propertyKey][parametersSymbol] = target[propertyKey][parametersSymbol] || [];
      [].concat(adjustedParams || []).forEach(param => {
        target[propertyKey][parametersSymbol].push({ execution, name, params: param })
      })
      return processDescriptor(
        args => JSON.stringify(args),
        arg => getReporter().addArgument('inputs', arg),
        descriptor
      )
    }
  }
}
```
Would be greatly appreciated if you can share your thoughts on this. Is it worth implementing such features on `testdeck` level or it'd be better to implement it on a client-side?

**Comment by silkentrance** [comment]
@sskorol Hey, thank you. I see that you have a strong testing background and I think that your solution is absolutely on the right track.

I, too, am unhappy with the multiple `@params` decorators one needs to use in order to have multiple test cases per test method, hence this long term goal.

And, now that the core is rather stable, I actually wanted to start working on this.

As it is now, the factory will create a new wrapper for each test parameter set prior to that the actual tests are being run. This, of course, is not so good when having large data sets that need to be processed.

What I wanted to with here is to consolidate everything into a single approach, i.e. collect multiple `@params` decorations and make this a single parameter provider that will then be used to create test functions on the fly.

My initial analysis was to use a nested describe() for each such parameter provider, and within that describe, fetch the next set of test parameters and create a test function (it) on the fly.

This is basically the same approach when you create your tests dynamically, iterating over a set of test data and inside the handler function use `it(...)` to run the tests. In our case, the latter would then delegate the actual test to the method of the test suite class.

However, jest already has some abstraction for this and I wanted to also take that into account, possibly reusing jest specific features as they integrate more nicely into that framework.

As for mocha and jasmine, well, this would still use the old approach.

I also thought about adding support for promise based providers and even generator based providers using `yield`.

It has been a long time since I last looked into this, but I think that I already have some prototype code lying around somewhere, unless that got lost during the transition from mocha-typescript to testdeck.

Of course, an initial approach in the sense of an MVP for this feature would be to just pass in an iterator to the test method that would be required to iterate over the available test data. This, however, turns out to be rather nasty and requires a feature such as `Assertions.assertAll()` which is available in for example junit. I also implemented a similar functionality for use with the chai assertions framework, but I did not get around to publishing that package. (and where is that code...)

Regardless, this is still on the menu and work on this might start soon, once I finished up the rewrite of node-tmp.

**Comment by silkentrance** [comment]
@sskorol ATM I am also rather unhappy with the existing code base. While @pana-cc did a great job there when refactoring/rewriting the existing mocha-typescript, internally, everything is still rather hard core javascript callback stuff and hard to maintain/extend over the years.

I did work on a major refactoring/rewrite that used a pure object oriented approach. (now, where is that code again... macbook died a few months back.)

**Comment by silkentrance** [comment]
Closing for now. We can reopen this if there is a need for such a feature.
