### ISSUE TITLE
[BUG] - Are nested suites supported?

### ISSUE THREAD

**Issue by artemdanylenko** [testdeck/testdeck#242]
## Testdeck Version

0.0.6

## Testdeck Package

 - [+] `@testdeck/core`
 - [+] `@testdeck/mocha`
 - [+] `@testdeck/jasmine`
 - [ ] `@testdeck/jest`
 - [ ] unsure

## NodeJS Version

 - [+] 11
 - [ ] 10
 - [ ] 9
 - [ ] 8
 - [ ] all
 - [ ] other: 

## Mocha / Jasmine / Jest Version

 - Mocha:
 - `@types/mocha`: ^5.2.7
 - Jasmine:
 - `@types/jasmine`: ^3.4.0

### Operating System

 - [ ] Linux
 - [+] Mac OS X
 - [ ] Windows 7
 - [ ] Windows 10
 - [ ] Other:

### Actual Behaviour
Documentation describes
https://testdeck.org/pages/guide/nested
```
While in your favourite test framework you might be using nested describe, when using Testdeck you should use suite instead. And while you can still use describe, you should use suite, only. The rationale here being that we may add support for test frameworks that do not support describe.
```
There are 2 problems with this:
1) example does not compile, it is missing a closing `)`: 
```js
import { suite, test } from '@testdeck/jasmine';

suite('a suite', function() {

  suite('nested suite', function () {

    @suite
    class DeeplyNestedSuite {

      @test
      failingTest() {

        throw new Error('not implemented yet');
      }
    }
  }**);**
});
```
2) When this example is run - it produces 0 tests

### Expected Behaviour
1) Example is corrected
2) Nested suite declarations work as described

**Comment by silkentrance** [comment]
@artemdanylenko Thank your very much for finding this. This part of the documentation was made in a hurry and the provided examples have not been tested at all. *Shame on me*

Once the missing closing bracket and semicolon have been added, running the test will show that the tests will not be run.

This is due to the fact, that Mocha, Jasmine and Jest do not run any test suites that do not have any tests in them.

And having a nested suite as is presented in the non working example, will make all of the three frameworks skip the nested suite.

The actually works as expected but we surely want ``suite`` to behave in the same way.

```
describe("outer", function() {

  describe("inner", function() {

     it("should work", function () {
 
       throw new Error("but does not");
     });
  });
}));
```

**Comment by silkentrance** [comment]
https://github.com/testdeck/testdeck-site/pull/43
