### ISSUE TITLE
[QUESTION] - How can we execute beforeAll without static

### ISSUE THREAD

**Issue by zveljkovic** [testdeck/testdeck#246]
## Question
I need some of my DI objects in beforeAll, is there any non static version of beforeAll?
Namely, I want in below code to inject KafkaManager to create a new topic. I can DI only in constructor, and from within static before() I can't use instance variables...

```
@suite
@injectable()
class KafkaReaderTest {
  private static topicName: string = 'b-' + Utils.randomString();

  constructor(private kafkaManager: KafkaManager) {}

  static async before(): Promise<any> {
    await this.kafkaManager.createTopic({
      topic: this.topicName,
    })
  }
```

**Comment by zveljkovic** [comment]
at node_modules/@testdeck/core/dist/index.js after line 76 I have added the 
```
// Register the instance beforeAll method to be called before-each test method.
            if (prototype.beforeAll) {
              const settings = theTestUI.getSettings(prototype.beforeAll);
              if (isAsync(prototype.beforeAll)) {
                theTestUI.runner.beforeAll("instance beforeAll", wrap(function (done) {
                  return prototype.beforeAll.call(instance, done);
                }, prototype.beforeAll), settings);
              }
              else {
                theTestUI.runner.beforeAll("instance beforeAll", wrap(function () {
                  return prototype.beforeAll.call(instance);
                }, prototype.beforeAll), settings);
              }
            }
```

which solved the issue for me. Can you please check if that is what we need and I could make a PR for this and after all as instance methods?

**Comment by silkentrance** [comment]
@zveljkovic Thank you for your work.

However, this changes the semantics of the test suite.

Currently, the test class will be instantiated before each test and not just once beforeAll tests.

This has both historical as well as practical reasons, as you will not have to clean up after each test in order to get a clean state.

As such, we cannot change this behaviour as it would otherwise break existing test suites out there in the field.

Your best bet is actually the constructor of your test suite, which acts similar to a surrounding `describe` and the scope that it will provide for the nested `it`S.

**Comment by silkentrance** [comment]
However, and if you need longer living instances of say a kafka consumer or other service connectors, your best bet is to allocate them in the constructor as static variables of your class, e.g.

```
@suite class WithStaticState {

  private static SERVICE_CONNECTOR : ServiceConnector;

  constructor() {
     if (WithStaticState.SERVICE_CONNECTOR == null) {
       WithStaticState.SERVICE_CONNECTOR = ...;
     }
  }

}
```

And since you are using dependency injection, the instance of the service (connector) are maintained by the container, so why even bother? Depending on the container being used, the container will keep the service instances alive, even make them singletons, and hand out the same instance over and over again.

As such, the longevity state was already refactored out to the container and you can simply just inject that into your constructor.

**Comment by silkentrance** [comment]
Coming back to your example this would then mean

```
@suite
@injectable()
class KafkaReaderTest {
  private static topicName: string = 'b-' + Utils.randomString();
  private static bool topicCreated = false;

  constructor(private kafkaManager: KafkaManager) {}

  async before(): Promise<any> {
    if (!KafkaReaderTest.topicCreated) {
      await this.kafkaManager.createTopic({
        topic: this.topicName,
      });
    }
  }
```

or something similar along that line.

**Comment by silkentrance** [comment]
Closing as this can be resolved using standard language paradigms instead of introducing an altogether new behaviour to testdeck, which in fact would break existing mocha-typescript behaviour, making it difficult to migrate from mocha-typescript to testdeck/mocha.

**Comment by zveljkovic** [comment]
Hi and thanks for your response. Everything is clear and I agree with your thoughts on the subject. I have made a simple Inversify handler myself, but it would be nice for other users to have one implementation in the core/docs.

**Comment by panayot-cankov** [comment]
If I understand correctly the long-story-short is we need DI to resolve arguments in lifecycle hooks and test methods.

**Comment by silkentrance** [comment]
@panayot-cankov great to have you back, as I have been busy with studying and doing my own stuff.
yes, that it what was proposed, as you might remember, far back in the past. nevertheless, I do not have any time to implement this, nor update the existing documentation.

**Comment by silkentrance** [comment]
apart from that, before all needs to be a static hook and cannot be executed otherwise, which was indeed the original question.
and yes, injecting these in before or even test methods would be great.

**Comment by pana-cc** [comment]
I feel like doing this over the weekend.

**Comment by silkentrance** [comment]
beforeall is always static and this cannot be changed.

**Comment by pana-cc** [comment]
Do we have DI hooks for before and after?

**Comment by silkentrance** [comment]
@pana-cc 

The injection takes place at the constructor level only, see the di-typedi package.

I don't see why user can't use a helper class that is a singleton that would then provide such facilities like kafka etc.

```
@Singleton
class KafkaFacility {
}



@suite
class MySuite {

   static before() {
       KafkaFacility.getInstance()...
   }

    static after() {
        KafkaFacility.getInstance()...
    }
}
```

**Comment by silkentrance** [comment]
To put `static before` into context of the supported test frameworks

```
describe('...', function () {
    beforeAll(...);
    ...
    afterAll(...);
})
```
